# Generated by Django 4.2.1 on 2023-05-08 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(unique=True, validators=[django.core.validators.RegexValidator('^#([0-9a-f]{6}|[0-9a-f]{3})$', 'Введите верное значение HEX-кода')], verbose_name='цвет'),
        ),
    ]
